# Generated by Django 5.1.3 on 2024-12-14 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0002_dpi_medecin_dpi_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dpi',
            name='medecin',
        ),
        migrations.RemoveField(
            model_name='dpi',
            name='patient',
        ),
    ]
