# Generated by Django 5.1.3 on 2024-12-20 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0005_alter_dpi_qr_code'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpi',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dpi', to='users.patient'),
        ),
    ]
