# Generated by Django 5.1.3 on 2024-12-21 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0007_alter_dpi_medecin_consultation_biologique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='resume',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_diagnostic', to='dpi.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree', models.IntegerField(help_text='Duration of the prescription in days')),
                ('is_valid', models.BooleanField(default=False)),
                ('diagnostic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic', to='dpi.diagnostic')),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('duree', models.IntegerField(help_text='Duration of the prescription in days')),
                ('dose', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('dosePrise', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('dosePrevues', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meds', to='dpi.ordonnance')),
            ],
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='ordonnance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnance', to='dpi.ordonnance'),
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
