# Generated by Django 5.1.3 on 2024-12-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0009_remove_biologique_consultation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biologique',
            name='tauxPressionArterielle',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
