# Generated by Django 5.1.3 on 2024-12-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0010_remove_ordonnance_diagnostic'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='dose_prescrite',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='est_injection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicament',
            name='frequence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='mode_administration',
            field=models.CharField(blank=True, choices=[('IM', 'Intramusculaire'), ('IV', 'Intraveineuse'), ('SC', 'Sous-cutanée'), ('ID', 'Intradermique'), ('PO', 'Orale'), ('PR', 'Rectale'), ('PV', 'Vaginale'), ('INH', 'Par inhalation'), ('NAS', 'Nasale'), ('TOP', 'Topique (locale)'), ('OC', 'Oculaire'), ('AU', 'Auriculaire'), ('SL', 'Sublinguale'), ('BUCC', 'Buccale'), ('TD', 'Transdermique')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='unite',
            field=models.CharField(blank=True, choices=[('mg', 'Milligramme'), ('g', 'Gramme'), ('ml', 'Millilitre'), ('l', 'Litre'), ('cl', 'Centilitre'), ('ng', 'Nanogramme'), ('pg', 'Picogramme')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='duree',
            field=models.IntegerField(),
        ),
    ]
