# Generated by Django 5.1.3 on 2024-12-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0010_alter_biologique_tauxpressionarterielle'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='is_bilanBiologique_fait',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='is_bilanRadiologique_fait',
            field=models.BooleanField(default=False),
        ),
    ]
