# Generated by Django 5.1.3 on 2024-12-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0011_medicament_dose_prescrite_medicament_est_injection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicament',
            name='est_injection',
        ),
        migrations.AddField(
            model_name='medicament',
            name='qte',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='dose',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='dosePrevues',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='dosePrise',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='mode_administration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='unite',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
