# Generated by Django 5.1.3 on 2024-12-27 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0012_consultation_graphebiologique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationMeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist', models.JSONField(blank=True, default=dict)),
                ('ordonnance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administration_meds', to='dpi.ordonnance')),
            ],
        ),
        migrations.CreateModel(
            name='Soin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField()),
                ('soins_infermier', models.JSONField(blank=True, default=list)),
                ('aministration', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administration_meds', to='dpi.administrationmeds')),
                ('dpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soins', to='dpi.dpi')),
                ('infermiers', models.ManyToManyField(limit_choices_to={'role': 'infermier'}, related_name='assigned_soins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
