# Generated by Django 5.1.3 on 2024-12-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0012_remove_medicament_est_injection_medicament_qte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordonnance',
            name='duree',
            field=models.IntegerField(blank=True, help_text='Duration of the prescription in days', null=True),
        ),
    ]
