# Generated by Django 5.1.3 on 2024-12-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0013_alter_ordonnance_duree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='unite',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
