# Generated by Django 5.1.3 on 2024-12-24 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0012_consultation_graphebiologique'),
        ('dpi', '0014_alter_medicament_unite'),
    ]

    operations = [
    ]
