# Generated by Django 5.1.3 on 2024-12-24 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0015_merge_20241224_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicament',
            name='dose_prescrite',
        ),
    ]
