# Generated by Django 5.1.3 on 2024-12-28 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0013_administrationmeds_soin'),
        ('dpi', '0016_remove_medicament_dose_prescrite'),
    ]

    operations = [
    ]
