# Generated by Django 5.1.3 on 2024-12-28 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0017_merge_20241228_0244'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soin',
            name='infermiers',
        ),
        migrations.RemoveField(
            model_name='soin',
            name='observation',
        ),
        migrations.CreateModel(
            name='SoinInfermierObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField()),
                ('soins_infermier', models.TextField()),
                ('infermier', models.ForeignKey(blank=True, limit_choices_to={'role': 'infermier'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_soins_infermiers', to=settings.AUTH_USER_MODEL)),
                ('soin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='dpi.soin')),
            ],
        ),
    ]
