# Generated by Django 5.1.3 on 2024-12-28 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0018_remove_soin_infermiers_remove_soin_observation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soin',
            name='soins_infermier',
        ),
    ]
