# Generated by Django 5.1.3 on 2024-12-28 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0019_remove_soin_soins_infermier'),
    ]

    operations = [
        migrations.AddField(
            model_name='soin',
            name='diagnostic',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_soin', to='dpi.diagnostic'),
        ),
    ]
