# Generated by Django 5.1.3 on 2024-12-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0021_remove_soin_diagnostic_diagnostic_soin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicament',
            old_name='qte',
            new_name='cycle',
        ),
        migrations.AddField(
            model_name='medicament',
            name='lastPrise',
            field=models.DateField(blank=True, null=True),
        ),
    ]
