# Generated by Django 5.1.3 on 2024-12-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0022_rename_qte_medicament_cycle_medicament_lastprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='dosePrise',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
    ]
