# Generated by Django 5.1.3 on 2024-12-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0023_alter_medicament_doseprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='validation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
