# Generated by Django 5.1.4 on 2024-12-06 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='numero_securite_sociale',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='prenom',
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
