# Generated by Django 5.1.3 on 2024-12-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('adminCentral', 'Adminstrateur Central'), ('adminSys', 'Administrateur Systeme'), ('patient', 'Patient'), ('medecin', 'Medecin'), ('infermier', 'Infermier'), ('radioloque', 'Radioloque'), ('laborantin', 'Laborantin'), ('pharmacien', 'Pharmacien')], default='patient', max_length=20),
        ),
    ]
