# Generated by Django 5.1.3 on 2024-12-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_date_de_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mutuelle',
            field=models.FileField(blank=True, null=True, upload_to='mutuelle_pdfs/'),
        ),
    ]
